export let publicEndpoints = {
  brands: "/brands",
  carts: "/carts",
  categories: "/categories",
  products: "/products",
  productsSuggestion: "/products/suggests",
  countProductsOnSale: "/products/count-product-on-sale",
  register: "/auth/register",
  authenticate: "/auth/authenticate",
  verify: "/auth/verify",
  currentUser: "/auth/current-user",
  refreshToken: "/auth/refresh",
  customer: "/customers",
  orders: "/orders",
  trackingOrder: "/orders/tracking",
  payments: "/payments",
  updatePaymentStatus: "/payments/update-payment-status",
  paymentDestinations: "/payment-destinations",
};

export let privateEndpoints = {
  brands: "/admin/brands",
  categories: "/admin/categories",
  products: "/admin/products",
  orders: "/admin/orders",
  orderStatuses: "/admin/order-statuses",
  orderStatus: "/admin/order-statuses",
  deliveryCompanies: "/admin/delivery-companies",
  payments: "/admin/payments",
  updatePaymentStatus: "/admin/payments/update-payment-status",
  recreatePaymentUrl: "/admin/payments/recreate-payment-url",
};
